import Head from 'next/head';
import {BsGithub, BsTelegram, BsYoutube,} from 'react-icons/bs';
import {CgDarkMode} from 'react-icons/cg'
import { Inter } from '@next/font/google';
import Image from "next/image";
import wave from '../public/avatar.png';
import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Arfsar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 md:px-20 lg:px-40 bg-white dark:bg-black'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-bold text-gray-700 dark:text-gray-300'><i>DCylert</i></h1>
            <ul className='flex items-center'>
              <li>
                <CgDarkMode onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-gray-700 dark:text-gray-300 hover:text-gray-500'/>
              </li>
              <li><a className='bg-sky-500 hover:bg-sky-700 text-white px-4 py-2 rounded-md ml-8' href="#contact">Contact</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-sky-500 font-medium md:text-6xl'>
              M. Arif Amsar
              </h2>
            <h3 className='text-2xl py-2 md:text-3xl text-black dark:text-white'>Student of Informatics Engineering</h3>
            <p className='text-md py-5 leading-8 text-gray-700 md-text-xl max-w-xl mx-auto'>Currently studying on Informatics Engineering or Computer Science at University Islamic of Riau. And i'm curious to learning for make some website. Feel free to ask something!</p>
          </div>
          <div className='text-4xl text-center py-5 text-sky-500'>
            <h2>Find me on</h2>
          </div>
          <div id='contact' className='text-3xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-100'>
            <a href="https://github.com/dialgacylert"><BsGithub/></a>
            <a href="https://t.me/arfsar"><BsTelegram/></a>
            <a href="https://www.youtube.com/@muhammadarifamsar5037"><BsYoutube/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-sky-400 rounded-full w-80 h-80 mt-20 overflow-y-hidden md:h-96 md:w-96'>
            <Image src={wave}/>
          </div>
        </section>
      </main>
    </div>
  )
}
